name: Vue-Build

on:
  push:
    tags: ["v*.*.*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Toolchain info
        run: |
          node --version
          npm --version
      - name: Build
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: vkerl/trace-mgr
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: dist/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Deploy Svr
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.TRACE_SVR_HOST }}
          user: ${{ secrets.TRACE_SVR_USERNAME }}
          pass: ${{ secrets.TRACE_SVR_PWD }}
          port: ${{ secrets.TRACE_SVR_PORT }}
          connect_timeout: 10s
          scp: |
            './docker-compose.yaml' => ~/data0/upload/trace-mgr/
          last_ssh: |
            cd ~/data0/upload/trace-mgr/
            ./startup.sh

